name: roadmap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  hooks_riverpod: ^2.3.8
  pedantic_mono: ^1.21.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
