name: roadmap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  build_runner: ^2.4.6
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.4.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  google_fonts: ^6.0.0
  google_sign_in: ^6.1.5
  hooks_riverpod: ^2.3.8
  line_awesome_flutter: ^2.0.0
  liquid_swipe: ^3.1.0
  logger: ^2.0.2
  pedantic_mono: ^1.21.1
  smooth_page_indicator: ^1.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/fonts/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
