# ワークフロー名
name: 'Flutter Analyze'

# トリガー
on:

  # PR作成 or 更新時
  pull_request:
    types:
      - opened
      - synchronize

  # main or develop ブランチに push時
  push:
    branches:
      - main
      - develop

# 実行するジョブ
jobs:

  # ジョブ名
  flutter_analyze:

    # ジョブを実行するOS
    runs-on: ubuntu-latest

    # タイムアウト時間を設定
    timeout-minutes: 5

    # 実行したいアクションを設定
    steps:

      # ソースコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # セットアップ
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Flutterのバージョンを表示
      - name: Display Flutter Version
        run: flutter --version

      # flutter pub get を実行
      - name: Install Dependencies
        run: flutter pub get

      # 静的解析を実行
      - name: Run Flutter Analyze
        run: flutter analyze
